# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:43:55+00:00

from __future__ import annotations

from enum import Enum


class SortOrder(Enum):
    ASC = 'ASC'
    DESC = 'DESC'


class Format(Enum):
    json = 'json'
    jsonp = 'jsonp'
