# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:43:55+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel


class Isbn(BaseModel):
    isbn10: Optional[str] = None
    isbn13: Optional[str] = None


class Book(BaseModel):
    age_group: Optional[str] = None
    amazon_product_url: Optional[str] = None
    article_chapter_link: Optional[str] = None
    asterisk: Optional[int] = None
    author: Optional[str] = None
    book_image: Optional[str] = None
    book_review_link: Optional[str] = None
    contributor: Optional[str] = None
    contributor_note: Optional[str] = None
    dagger: Optional[int] = None
    description: Optional[str] = None
    first_chapter_link: Optional[str] = None
    isbns: Optional[List[Isbn]] = None
    price: Optional[int] = None
    primary_isbn10: Optional[str] = None
    primary_isbn13: Optional[str] = None
    publisher: Optional[str] = None
    rank: Optional[int] = None
    rank_last_week: Optional[int] = None
    sunday_review_link: Optional[str] = None
    title: Optional[str] = None
    weeks_on_list: Optional[int] = None


class Results(BaseModel):
    bestsellers_date: Optional[str] = None
    books: Optional[List[Book]] = None
    corrections: Optional[List[Dict[str, Any]]] = None
    display_name: Optional[str] = None
    list_name: Optional[str] = None
    normal_list_ends_at: Optional[int] = None
    published_date: Optional[str] = None
    updated: Optional[str] = None


class JsonGetResponse(BaseModel):
    copyright: Optional[str] = None
    last_modified: Optional[str] = None
    num_results: Optional[int] = None
    results: Optional[Results] = None
    status: Optional[str] = None
