# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:43:55+00:00

from __future__ import annotations

from typing import Any, List, Optional

from pydantic import BaseModel


class Isbn(BaseModel):
    isbn10: Optional[str] = None
    isbn13: Optional[str] = None


class RanksHistoryItem(BaseModel):
    asterisk: Optional[int] = None
    bestsellers_date: Optional[str] = None
    dagger: Optional[int] = None
    display_name: Optional[str] = None
    list_name: Optional[str] = None
    primary_isbn10: Optional[str] = None
    primary_isbn13: Optional[str] = None
    published_date: Optional[str] = None
    rank: Optional[int] = None
    ranks_last_week: Optional[Any] = None
    weeks_on_list: Optional[int] = None


class Review(BaseModel):
    article_chapter_link: Optional[str] = None
    book_review_link: Optional[str] = None
    first_chapter_link: Optional[str] = None
    sunday_review_link: Optional[str] = None


class Result(BaseModel):
    age_group: Optional[str] = None
    author: Optional[str] = None
    contributor: Optional[str] = None
    contributor_note: Optional[str] = None
    description: Optional[str] = None
    isbns: Optional[List[Isbn]] = None
    price: Optional[int] = None
    publisher: Optional[str] = None
    ranks_history: Optional[List[RanksHistoryItem]] = None
    reviews: Optional[List[Review]] = None
    title: Optional[str] = None


class JsonGetResponse(BaseModel):
    copyright: Optional[str] = None
    num_results: Optional[int] = None
    results: Optional[List[Result]] = None
    status: Optional[str] = None
