# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:43:55+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class Book(BaseModel):
    age_group: Optional[str] = None
    author: Optional[str] = None
    contributor: Optional[str] = None
    contributor_note: Optional[str] = None
    created_date: Optional[str] = None
    description: Optional[str] = None
    price: Optional[int] = None
    primary_isbn10: Optional[str] = None
    primary_isbn13: Optional[str] = None
    publisher: Optional[str] = None
    rank: Optional[int] = None
    title: Optional[str] = None
    updated_date: Optional[str] = None


class ListModel(BaseModel):
    books: Optional[List[Book]] = None
    display_name: Optional[str] = None
    list_id: Optional[int] = None
    list_image: Optional[str] = None
    list_name: Optional[str] = None
    updated: Optional[str] = None


class Results(BaseModel):
    bestsellers_date: Optional[str] = None
    lists: Optional[List[ListModel]] = None
    published_date: Optional[str] = None


class FieldFormatGetResponse(BaseModel):
    copyright: Optional[str] = None
    num_results: Optional[int] = None
    results: Optional[Results] = None
    status: Optional[str] = None
