# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:43:55+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class Result(BaseModel):
    display_name: Optional[str] = None
    list_name: Optional[str] = None
    list_name_encoded: Optional[str] = None
    newest_published_date: Optional[str] = None
    oldest_published_date: Optional[str] = None
    updated: Optional[str] = None


class FieldFormatGetResponse(BaseModel):
    copyright: Optional[str] = None
    num_results: Optional[int] = None
    results: Optional[List[Result]] = None
    status: Optional[str] = None
