# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:43:55+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class Result(BaseModel):
    book_author: Optional[str] = None
    book_title: Optional[str] = None
    byline: Optional[str] = None
    isbn13: Optional[List[str]] = None
    publication_dt: Optional[str] = None
    summary: Optional[str] = None
    url: Optional[str] = None


class FieldFormatGetResponse(BaseModel):
    copyright: Optional[str] = None
    num_results: Optional[int] = None
    results: Optional[List[Result]] = None
    status: Optional[str] = None
